[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Crop-My-GIF"
authors = [{name = "MachWheel", email = "wyller22@gmail.com"}]
dynamic = ["version", "description"]
